/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <stdio.h>
#define USART3_IRQ 39
int main(void)
{	uint32_t volatile *IPCER= (uint32_t*)(0xE000E204);
	uint32_t volatile *ISCER= (uint32_t*)(0xE000E104);

	*IPCER |= (1<<(USART3_IRQ%32));
	*ISCER |= (1<<(USART3_IRQ%32));
	/* Loop forever */

}

void USART3_IRQHandler (void){
	printf("Handler Mode\n");
}
