/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

int32_t add (int x,int y){
	int res;
	__asm ("SVC #36");
	__asm ("MOV %0,r0":"=r"(res)::);
	return res;
}
int32_t substruct (int x,int y){
	int res;
	__asm("SVC #37");
	__asm ("MOV %0,R0":"=r"(res)::);
	return res;
}
int32_t multiply (int x,int y){
	int res;
	__asm ("SVC #38");
	__asm ("MOV %0,R0":"=r"(res)::);
	return res;
}
int32_t divide (int x,int y){
	int res;
	__asm ("SVC #39");
	__asm ("MOV %0,R0":"=r"(res)::);
	return res;
}

int main(void)
{	//__asm volatile ("SVC #0x05");
    /* Loop forever */
//	register uint32_t data __asm("r0");
//	printf("%d\n",data);
	divide(8,0);
	for(;;);
}
__attribute__((naked)) SVC_Handler (void){
	__asm ("MRS R0,MSP");
	__asm ("b SVC_Handler_c");
}
void SVC_Handler_c(uint32_t *masked){

	int8_t a= masked[0];
	int8_t b =masked[1];
	uint8_t *ptr=(uint8_t*)(masked[6]);
	ptr-=2;
	printf("%d\n",*ptr);
	int8_t res;
	switch(*ptr){
	case (36): res=a+b;
		break;
	case (37): res=a-b;
		break;
	case (38) : res=a*b;
		break;
	case (39): res=a/b;
		break;
	}
	masked[0]=res;
}

void HardFault_Handler(void){
	printf("Divide by Zero\n");
	while(1);

}
