/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define I2C1_EV 31
#define TIM2 28

uint32_t volatile *ISER=(uint32_t*)(0xE000E100);
uint32_t volatile *IPER=(uint32_t*)(0XE000E200);
uint32_t volatile *IPR=(uint32_t*)(0xE000E400);

void configure_pri(int event, int value){

	uint32_t volatile *ptr=(IPR+(event/4));
	*ptr &= ~(0xFF<<((event%4)*8));
	*ptr |= (value<<((event%4)*8));
}
int main(void)
{
	configure_pri(I2C1_EV,0x80);
	configure_pri(TIM2,0x80);

	*IPER |= (1<<TIM2);

	*ISER |= (1<<I2C1_EV);
	*ISER |= (1<<TIM2);
	/* Loop forever */

	for(;;);
}
void TIM2_IRQHandler(void){
	printf("[TIM2 Handler]\n");
	*IPER |= (1<<I2C1_EV);
	while(1);
}
void I2C1_EV_IRQHandler (void){
	printf("[I2C1_Handler]\n");
}
