/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



int main(void)
{
	uint32_t volatile* address_RCC_CR = (uint32_t*)(0x40023800);
	uint32_t volatile* address_RCC_C =(uint32_t*)(0x40023800+0x08);
	*address_RCC_CR |= (1<<16);
	while(!(*address_RCC_CR & (1<<17)));

	*address_RCC_C |= 1;

	*address_RCC_C &= ~(3<<21);
	*address_RCC_C |= (1<<22);

	*address_RCC_C |= (3<<25);
	uint32_t volatile* const address_RCC = (uint32_t*)(0x40023800+0x30);
	uint32_t volatile* const address_GPIOMode = (uint32_t*)(0x40020000);
//	uint32_t volatile* const address_OUTPUT = (uint32_t*)(0x40020000+0x24);
	*address_RCC = *address_RCC | 1;
	*address_GPIOMode &= ~(3<<16);
	*address_GPIOMode=*address_GPIOMode | (1<<17);
//	*address_OUTPUT=*address_OUTPUT | (1<<8);

    /* Loop forever */
	for(;;);
}
