/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

int main(void)
{	uint32_t volatile *const address_RCC = (uint32_t*)(0x40023830);
	uint32_t volatile *const address_Mode =(uint32_t*)(0x40021000);
	uint32_t volatile *const address_OUTPUT=(uint32_t*)(0x40021000+0x14);
	uint32_t volatile *const address_input =(uint32_t*)(0x40021000+0x10);
	uint32_t volatile *const address_pullup=(uint32_t*)(0x40021000+0x0C);

	// Enable the clock
	*address_RCC |= (1<<4);
	//Setting the Mode
	*address_Mode &= ~(0xFF<<14);
	*address_Mode |= (0x55<<14);
	*address_Mode &= ~(0x3F<<22);

	//Enable the pull up Register
	*address_pullup |= (0X15<<22);

	//Set Row pins to OUTPUT

    /* Loop forever */
	while(1){
		*address_OUTPUT |= (0X0F<<7);
		*address_OUTPUT &= ~(1<<7);
		if ( !(*address_input & (1<<11)) ){
			for(int i =0;i<500000 ;i++);
			printf("1 \n");
		}
		if ( !(*address_input & (1<<12)) ){
			for(int i =0;i<500000 ;i++);
			printf("2 \n");
		}
		if ( !(*address_input & (1<<13)) ){
			for(int i =0;i<500000 ;i++);
			printf("3 \n");
		}
		*address_OUTPUT |= (0X0F<<7);
		*address_OUTPUT &= ~(1<<8);
		if (! (*address_input & (1<<11)) ){
			for(int i =0;i<500000 ;i++);
			printf("4 \n");
		}
		if (! (*address_input & (1<<12)) ){
			for(int i =0;i<500000 ;i++);
			printf("5 \n");
		}
		if (! (*address_input & (1<<13)) ){
			for(int i =0;i<500000 ;i++);
			printf("6 \n");
		}
		*address_OUTPUT |= (0X0F<<7);
		*address_OUTPUT &= ~(1<<9);
		if (! (*address_input & (1<<11)) ){
			for(int i =0;i<500000 ;i++);
			printf("7 \n");
		}
		if (! (*address_input & (1<<12)) ){
			for(int i =0;i<500000 ;i++);
			printf("8 \n");
		}
		if (! (*address_input & (1<<13)) ){
			for(int i =0;i<500000 ;i++);
			printf("9 \n");
		}
		*address_OUTPUT |= (0X0F<<7);
		*address_OUTPUT &= ~(1<<10);
		if (! (*address_input & (1<<11)) ){
			for(int i =0;i<500000 ;i++);
			printf("* \n");
		}
		if (! (*address_input & (1<<12)) ){
			for(int i =0;i<500000 ;i++);
			printf("0 \n");
		}
		if (! (*address_input & (1<<13)) ){
			for(int i =0;i<500000 ;i++);
			printf("# \n");
		}

	};
}
