/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"
#include <stdio.h>
void delay(void){
	for(int i=0;i<50000;i++);
}
int main(void)
{	GPIO_Handle_t gpioA;
    /* Loop forever */
	GPIO_PeriClockControl(GPIOB_REG,ENABLE);
//	printf("%p \n",gpioA.pGPIOx->MODER);
	gpioA.pGPIOx = GPIOB_REG;
	gpioA.GPIO_PinConfig.PinMode = GPIO_MODE_OUT;
//	printf("%p \n",gpioA.pGPIOx->MODER);
	gpioA.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_13;
	gpioA.GPIO_PinConfig.PinOPType = GPIO_OP_TYPE_PP;
	gpioA.GPIO_PinConfig.PinPuPdControl = GPIO_NO_PUPD;
	gpioA.GPIO_PinConfig.PinSpeed = GPIO_OSPEED_MED;

	GPIO_init(&gpioA);



	GPIO_WriteToOutputPin(GPIOB_REG, 13,LOW);
	delay();



	for(;;);
}
